<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { Menu, Moon, Sun, UserRound, X, LogOut } from 'lucide-vue-next'
import { RouterLink, RouterView, useRouter } from 'vue-router'
import ButterflyDecor from './components/butterfly-decor.vue'
import { requestApi } from './services/api'
const router=useRouter();const menuOpen=ref(false);const theme=ref(localStorage.getItem('myblog-theme')||'light');const userRole=ref(localStorage.getItem('myblog-user-role')||'');const isDark=computed(()=>theme.value==='dark');const isLoggedIn=computed(()=>Boolean(localStorage.getItem('myblog-token')));const isAuthor=computed(()=>['author','admin'].includes(userRole.value))
function switchPageTheme(){theme.value=isDark.value?'light':'dark';localStorage.setItem('myblog-theme',theme.value);document.documentElement.dataset.theme=theme.value}
function syncUserRole(){userRole.value=localStorage.getItem('myblog-user-role')||''}
async function logoutUser(){try{if(isLoggedIn.value)await requestApi('/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('myblog-token');localStorage.removeItem('myblog-user-role');localStorage.removeItem('myblog-user');syncUserRole();window.dispatchEvent(new Event('myblog-auth-changed'));router.push('/')}
document.documentElement.dataset.theme=theme.value
onMounted(()=>window.addEventListener('myblog-auth-changed',syncUserRole));onUnmounted(()=>window.removeEventListener('myblog-auth-changed',syncUserRole))
</script>
<template><div class="site-shell"><header class="topbar"><RouterLink class="brand" to="/" @click="menuOpen=false"><span class="brand-mark">折</span><span>折页</span></RouterLink><nav :class="{open:menuOpen}"><RouterLink to="/" @click="menuOpen=false">首页</RouterLink><RouterLink to="/archive" @click="menuOpen=false">文章</RouterLink><RouterLink to="/messages" @click="menuOpen=false">留言</RouterLink><RouterLink to="/about" @click="menuOpen=false">关于我</RouterLink><RouterLink to="/timeline" @click="menuOpen=false">大事记</RouterLink><RouterLink to="/interests" @click="menuOpen=false">兴趣</RouterLink><RouterLink to="/friends" @click="menuOpen=false">友链</RouterLink><RouterLink to="/game" @click="menuOpen=false">小游戏</RouterLink><RouterLink to="/private" @click="menuOpen=false">秘密基地</RouterLink><RouterLink v-if="isAuthor" to="/studio" @click="menuOpen=false">作者后台</RouterLink><RouterLink v-if="isAuthor" to="/analytics" @click="menuOpen=false">数据分析</RouterLink><RouterLink v-if="isLoggedIn" to="/settings" @click="menuOpen=false">账号设置</RouterLink></nav><div class="top-actions"><button class="icon-button" title="切换主题" @click="switchPageTheme"><Sun v-if="isDark" :size="18"/><Moon v-else :size="18"/></button><button v-if="isLoggedIn" class="icon-button" title="退出登录" @click="logoutUser"><LogOut :size="18"/></button><RouterLink v-else class="icon-button" title="登录" to="/login"><UserRound :size="18"/></RouterLink><button class="icon-button mobile-menu" title="打开菜单" @click="menuOpen=!menuOpen"><X v-if="menuOpen" :size="20"/><Menu v-else :size="20"/></button></div></header><main class="page-transition"><RouterView/></main><ButterflyDecor/><footer class="footer"><span>折页 / ZHEYE</span><span>记录微小，保持好奇。© 2026</span><span>用心构建 / Built with patience.</span></footer></div></template>

