<script setup>
import { onMounted, ref } from 'vue'
import { MessageCircle, Send } from 'lucide-vue-next'
import { requestApi } from '../services/api'
const messageContent=ref('');const messages=ref([]);const replies=ref({});const replyInputs=ref({});const status=ref('');const loading=ref(true);const submitting=ref(false)
async function loadMessages(){loading.value=true;try{const result=await requestApi('/messages');messages.value=result.data}catch(error){status.value=error.message}finally{loading.value=false}}
async function publishMessage(){if(!messageContent.value.trim())return status.value='请先写下一点内容';submitting.value=true;try{await requestApi('/messages',{method:'POST',body:JSON.stringify({content:messageContent.value})});messageContent.value='';status.value='留言已发布';await loadMessages()}catch(error){status.value=error.message}finally{submitting.value=false}}
async function loadReplies(id){try{const result=await requestApi(`/messages/${id}/replies`);replies.value={...replies.value,[id]:result.data}}catch(error){status.value=error.message}}
async function replyMessage(id){const content=(replyInputs.value[id]||'').trim();if(!content)return status.value='回复内容不能为空';try{await requestApi(`/messages/${id}/replies`,{method:'POST',body:JSON.stringify({content})});replyInputs.value={...replyInputs.value,[id]:''};await loadReplies(id)}catch(error){status.value=error.message}}
onMounted(loadMessages)
</script>
<template><section class="content-narrow message-page"><div class="page-intro"><p class="eyebrow">留言板 / GUESTBOOK</p><h1>留下一点<br /><em>回声。</em></h1><p>欢迎留下关于项目、技术文章或网站体验的反馈。</p></div><div class="message-form"><textarea v-model="messageContent" maxlength="200" placeholder="写下你的留言..." /><div><span>{{status||`${messageContent.length} / 200`}}</span><button class="button button-primary" :disabled="submitting" @click="publishMessage">发送留言 <Send :size="15" /></button></div></div><div v-if="loading" class="empty-state">正在加载留言...</div><div v-else-if="!messages.length" class="empty-state">还没有留言，欢迎成为第一个留言的人。</div><div v-else class="message-list"><article v-for="message in messages" :key="message.id" class="message-item"><div class="message-avatar">{{message.author.slice(0,1)}}</div><div><div class="message-meta"><strong>{{message.author}}</strong><span>{{new Date(message.createdAt).toLocaleString()}}</span></div><p>{{message.content}}</p><button class="text-link" @click="loadReplies(message.id)"><MessageCircle :size="14" /> 查看回复</button><div v-if="replies[message.id]" class="reply-list"><div v-for="reply in replies[message.id]" :key="reply.id">{{reply.author}}：{{reply.content}}</div><span v-if="!replies[message.id].length" class="muted">暂无回复内容</span><div class="reply-form"><input v-model="replyInputs[message.id]" placeholder="写下回复" maxlength="200" /><button @click="replyMessage(message.id)">回复</button></div></div></div></article></div></section></template>
