<script setup>
import { onMounted, ref } from 'vue'
import { BarChart3, FilePenLine, LayoutDashboard, Plus, Save, Trash2, Upload } from 'lucide-vue-next'
import { createDraft, deleteDraft as requestDeleteDraft, getDrafts, publishDraft, updateDraft } from '../services/api'
const drafts = ref([]); const selected = ref(null); const saved = ref(true); const loading = ref(true); const saving = ref(false); const status = ref(''); const searchKeyword = ref('')
async function loadDrafts() { loading.value = true; try { const result = await getDrafts(searchKeyword.value); drafts.value = result.data; if (!selected.value || !drafts.value.some(draft => draft.id === selected.value.id)) selected.value = drafts.value[0] || null; saved.value = true } catch (error) { status.value = error.message } finally { loading.value = false } }
async function createNewDraft() { try { const result = await createDraft(); drafts.value.unshift(result.data); selected.value = result.data; saved.value = true; status.value = '草稿已创建' } catch (error) { status.value = error.message } }
function markChanged() { saved.value = false; status.value = '' }
async function saveDraft() { if (!selected.value) return; saving.value = true; try { const result = await updateDraft(selected.value.id, selected.value); selected.value = result.data; drafts.value = drafts.value.map(draft => draft.id === result.data.id ? result.data : draft); saved.value = true; status.value = '草稿已保存' } catch (error) { status.value = error.message } finally { saving.value = false } }
async function removeDraft() { if (!selected.value || !window.confirm('确定删除这篇草稿吗？')) return; try { await requestDeleteDraft(selected.value.id); status.value = '草稿已删除'; await loadDrafts() } catch (error) { status.value = error.message } }
async function publishSelected() { if (!selected.value || !window.confirm('确定发布这篇文章吗？')) return; try { await publishDraft(selected.value.id); status.value = '文章已发布'; await loadDrafts() } catch (error) { status.value = error.message } }
onMounted(loadDrafts)
</script>
<template><section class="studio content-wide"><div class="studio-top"><div><p class="eyebrow">作者后台 / AUTHOR STUDIO</p><h1>作者后台</h1></div><div class="studio-actions"><span class="save-state">{{ status || (saved ? '已保存' : '有未保存修改') }}</span><button class="button button-primary" @click="createNewDraft"><Plus :size="16" /> 新建草稿</button></div></div><div class="studio-layout"><aside class="studio-nav"><a class="active"><LayoutDashboard :size="16" />概览</a><a><FilePenLine :size="16" />草稿箱 <b>{{ drafts.length }}</b></a><a><BarChart3 :size="16" />数据分析</a></aside><div class="studio-main"><div class="draft-list"><div class="studio-section-title"><h2>我的草稿</h2><span>仅自己可见</span></div><div class="search-box"><input v-model="searchKeyword" placeholder="搜索草稿" @keyup.enter="loadDrafts" /></div><div v-if="loading" class="empty-state">正在加载草稿...</div><template v-else><button v-for="draft in drafts" :key="draft.id" class="draft-item" :class="{ selected: selected?.id === draft.id }" @click="selected = draft; saved = true"><span class="draft-status"></span><span><strong>{{ draft.title || '未命名草稿' }}</strong><small>{{ new Date(draft.updatedAt).toLocaleString() }}</small></span></button><div v-if="!drafts.length" class="empty-state">还没有草稿，开始写下第一篇吧。</div></template></div><div v-if="selected" class="editor-panel"><input v-model="selected.title" class="editor-title" placeholder="文章标题" @input="markChanged" /><textarea v-model="selected.content" class="editor-text" placeholder="从这里开始写 Markdown 内容..." @input="markChanged"></textarea><div class="editor-footer"><span>风险检测：{{ selected.title.trim().length < 2 ? '标题至少需要 2 个字' : !selected.content.trim() ? '正文不能为空' : '基础检查已通过' }}</span><div><button class="icon-button danger" title="删除草稿" @click="removeDraft"><Trash2 :size="17" /></button><button class="button" @click="publishSelected"><Upload :size="16" /> 发布</button><button class="button button-primary" :disabled="saving || saved" @click="saveDraft"><Save :size="16" /> {{ saving ? '保存中...' : '保存草稿' }}</button></div></div></div><div v-else-if="!loading" class="editor-panel empty-state">请选择草稿或新建一篇草稿。</div></div></div></section></template>

